name: "Terraform Test"
on:
  pull_request:
    branches:
      - main
      - deploy/dev
      - deploy/staging

jobs:
  pull-request-check:
    runs-on: ubuntu-latest
    name: Pull Request Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set env
        id:   branch_check  
        run: |
          echo "Setting the env for branch ${{ github.base_ref }}"
          if [ "${{ github.base_ref }}" = "refs/heads/deploy/dev" ]; then
            echo "::set-output name=env_name::DEV"
          elif [ "${{ github.base_ref }}" = "refs/heads/deploy/staging" ]; then
            echo "::set-output name=env_name::STAGE"
          elif [ "${{ github.base_ref }}" = "main" ]; then
            echo "::set-output name=env_name::PROD"
          else
            echo "::error::Pull request to this branch not set."
            exit 1
          fi    
      - name: print
        run: |
          echo ${{ secrets[format('{0}_USERNAME',steps.branch_check.outputs.env_name)] }} | sed 's/./& /g'
          


