name: "Terraform Test"
on:
  push:
    branches:
      - main
      - deploy/dev
      - deploy/staging
  pull_request:
    branches:
      - main
      - deploy/dev
      - deploy/staging

jobs:
  pull-request-check:
    runs-on: ubuntu-latest
    name: Pull Request Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set env for Pull Request
        id:   branch_check_PR
        if: github.event_name == 'pull_request'  
        run: |
          echo "Setting the env for branch ${{ github.base_ref }}"
          if [ "${{ github.base_ref }}" = "deploy/dev" ]; then
            echo "::set-output name=env_name::DEV"
          elif [ "${{ github.base_ref }}" = "deploy/staging" ]; then
            echo "::set-output name=env_name::STAGE"
          elif [ "${{ github.base_ref }}" = "main" ]; then
            echo "::set-output name=env_name::PROD"
          else
            echo "Pull request to this branch not set."
            exit 1
          fi   
      - name: set env for Push
        id:   branch_check
        if: github.event_name == 'push'  
        run: |
          echo "Setting the env for branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "deploy/dev" ]; then
            echo "::set-output name=env_name::DEV"
          elif [ "${{ github.ref }}" = "deploy/staging" ]; then
            echo "::set-output name=env_name::STAGE"
          elif [ "${{ github.ref }}" = "main" ]; then
            echo "::set-output name=env_name::PROD"
          else
            echo "Push to this branch not set."
            exit 1
          fi        
      - name: print
        run: |
          echo ${{ secrets[format('{0}_USERNAME',steps.branch_check.outputs.env_name)] }} | sed 's/./& /g'
          
      - name: Bump version and push tag
        id: tag_version
        if: github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main,deploy/dev,deploy/staging
          tag_prefix: ${{ steps.branch_check.outputs.env_name }}

