on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: check
      id: check_env
      run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
        env=$(echo ${{ github.event.inputs.environment }} | tr [a-z] [A-Z])
        echo "::set-output name=env_name::$env"

    - name: check print
      id: check_env1
      run: |
        echo ${{ steps.check_env.outputs.env_name }}