name: "Terraform Test"
on:
  push:
    branches:
      - main
      - deploy/dev
      - deploy/staging
      - t3est2
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    name: Pull Request Check
    steps:
    - name: Get list of changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: check
      id: check_env
      run: |
        echo "File Changed : ${{ steps.files.outputs.all }}"
        arrVar=()
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
          DIR=`echo ${changed_file} | grep -o '^.*/'`
          arrVar+=($DIR)
        done
        newArray=( `for i in ${arrVar[@]}; do echo $i; done | sort -u` )
        echo "${newArray[@]}" |
          jq -s '{dir: .}'`

    